### PR TITLE
Add docker image build workflow

### PR DESCRIPTION
**Pull request by vadyochik**
This creates container images for 3 archs (linux/386,linux/amd64,linux/arm64) and pushes to ghcr.io registry.
When need to build a new release version, change `ARG version=0.1.6` in the Dockerfile

### CODE REVIEW

**Comment by Yneth** [comment]
Looks great!

There is a slight delay between commit and actual release asset creation.
Guess either manual mode or https://github.com/marketplace/actions/release-github-actions 
would do the work!

**Comment by vadyochik** [comment]
Probably there is a need to change event trigger from "on push" to "on release" then?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

or to some other event. Or just add filter by `paths` like:

```
on:
  push:
    branches:    
      - 'main'
    paths:
      - 'Dockerfile'
```

I'm not sure about exact flow/steps of how you do these releases so just propossing available options.

**Comment by vadyochik** [comment]
here are some good examples that use "on release" event:

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by vadyochik** [comment]
I believe the event trigger should be changed to:

```
on:
  release:
    types: [released]
```

So this way you firstly publish a release, and only then the container image build workflow runs. Does it make sense ? Or am i missing something ?

**Comment by Yneth** [comment]
I re read your PR and got to understanding that I am overcomplicating and it should work as it is.
There could be a corner case when user unable to retrieve version as it is not published yet but I guess it would not be that much of a problem.
Will merge tomorrow!

**Comment by vadyochik** [comment]
I've changed event trigger to release instead of push to main branch. There is no sense to rebuild the image on every push to the branch, the image should be build only on releases.

**Pull request merged**
